/**
 * Created by test on 16/11/25.
 */
Lang.prototype.pack.zh = {
    "token":{
        "bitpie - Best Bitcoin Wallet!":"比特派-最好用的比特币钱包！",
        "About":"关于",
        "Features":"特色",
        "Contact":"联系我们",
        "Bitpie":"比特派",
        "Wallet & Ｍultisig Service":"钱包 & 多重签名服务",
        "Multisig Service":"多重签名服务",
        "Android":"安卓",
        "Download":"下载",
        "Google Play":"谷歌商店",
        "iOS":"苹果",
        "App Store":"苹果商店",
        "Bitpie is developed by":"比特派是由",
        "Bither":"比太",
        "team. With bitpie, you can have a secured bitcoin wallet as simple as possible, and you can also buy/sell bitcoins in an easy way(not available in China).":
            "团队研发的比特币钱包，它能让您轻松安全的使用比特币，并且还能方便的买卖比特币(不支持中国大陆)。",
        "Bitpie  supports multi-blockchain assets, so a wallet can manage everything. Try it now quickly!":
            "比特派支持多种区块链资产，您可以使用一个钱包来管理一切，赶紧试试吧！",
        "Wallets":"钱包",
        "Simpliest Bitcoin Wallet Ever!":"简单易用的比特币钱包！",
        "As a bitcoin wallet, bitpie means you control your private keys, and nobody can touch your assets. With our special design, you do not need to sync the blockchain data with the bitcon network, and sending/receiving bitcoins are processed so quickly. Also bitpie supports dynamic transaction fee and transaction accelerator, that means your transaction can easily go through even when network congestion.":
            "作为钱包，比特派意味着您自己掌握私钥，其他人无法触碰您的财产。通过我们的优化，您可以快捷的收发比特币，并且比特派还支持动态矿工费及交易加速器，这意味着即便是遇到了网络大拥堵，您的交易也能迅速得到确认。",
        "P2P Exchange:Easiest Way to Buy/Sell Bitcoins with Other Peers!":"P2P 交易：轻松的与其他人兑换比特币！",
        "Bitpie has built-in escrow function based on Multisig technology services, so you can easily exchange bitcoins with the dealers all over the world in a secured environment.":"比特派内置了基于多重签名技术服务，因此您可以安全的与世界各地的交易员兑换比特币。",
        "Security":"安全：",
        "Bither team has so many reputations in the past, and Bither wallet has been recommended by Bitcoin.org for a long time. We know how to make secured bitcoin wallet, and how to protect your blockchain assets. The bitpie wallet is totally based on Bither technology, so it is robust and trustable.":
            "比太团队在安全方面一直享有良好的声誉，比太钱包也是中国唯一一个被 Bitcoin.org 官方推荐的比特币钱包，我们懂得如何开发安全的比特币钱包以及如何保护您的区块链资产，比特派钱包完全基于比太技术，值得信赖。",
        "Bither team has so many reputations in the past, and Bither wallet has been recommended by":"比太团队在安全方面一直享有良好的声誉，比太钱包也是中国唯一一个被",
        "for a long time. We know how to make secured bitcoin wallet, and how to protect your blockchain assets. The bitpie wallet is totally based on Bither technology, so it is robust and trustable.":"官方推荐的比特币钱包，我们懂得如何开发安全的比特币钱包以及如何保护您的区块链资产，比特派钱包完全基于比太技术，值得信赖。",
        "Keep in Touch:":"保持联络",
        "P2P Exchange":"P2P 交易：",
        "Wallets":"钱包：",
        "Easiest Way To Exchange Bitcoins With Other Peers!":"轻松的与其他人兑换比特币！",
        "Email":"邮箱",
        "Telegram":"电报群(Telegram)",
        "QQ group 1:493077876":"QQ群1：493077876",
        "QQ group 2:431191173":"QQ群2：431191173",
        "QQ group 3:616697070":"QQ群3：616697070",
        "QQ group 4:602675609":"QQ群4：602675609",
        "QQ group 5:334102375":"QQ群5：334102375",
        "QQ group 6:41289311":"QQ群6：41289311",
        "Home":"首页",
        "The bitpie wallet is based on":"比特派钱包基于",
        "Bither":"比太",
        "technology.":"技术.",
        "Bitpie Android":"比特派 安卓",
        "Bitpie iOS":'比特派 iOS',
        "Version:":"版本：",
        "Download":"下载",
        "Use your cell phone  to install by scaning the qr code":"或者用手机扫描下面的二维码安装",
        "Doc":"帮助",
        "BITPIE LIMITED was registered at Republic of Seychelles since 2015":"BITPIE LIMITED于2015年在塞舌尔共和国注册",
        "Bitpie iOS app is under operation of Bitpie Canada":"Bitpie iOS 版由 Bitpie Canada 运营",
        "Blog":"博客",
        "blog":"博客",
        "Written by":"作者",
        "Certificate":"证书",
        "Close":"关闭",
        "BITPIE Terms of Service":"比特派用户协议",
        "An easy-to-use wallet service, you can easily manage your multi-blockchain assets.":"易于使用的钱包服务使您可以轻松的管理多种区块链资产。",
        "Trade your asset with users all over the world in the build-in OTC and exchange(3rd party services).":"内置OTC及交易所(第三方服务)，让您方便的与世界各地的用户进行币币交易及OTC交易。",
        "By holding private key only by yourself, no one else can access your assets.":"通过您自己掌控私钥，没有其他人能够触碰您的资产。",
        "Build-in professional KYC/anti-fraud system and commit to meet regulation and compliance.":"内置专业KYC及防欺诈系统，致力于遵守监管和法律合规。",
        "Originate from Bither team, Bitpie team is made up of blockchain professionals and business experts from IT/ Financial industries based around the world.":"源自比太，比特派团队由来自世界多地的区块链技术专家和IT服务及金融行业的业务专家组成。",
        "With strong technical strength on blockchain and years of experience from operate bither wallet, Bitpie is devoted to be a service provider to bring global users with safe asset management and broad blockchain application access. With Bitpie, users can trade assets with others or use their asset in more coming scenarios meanwhile keep their asset 100% self-controllable.":"基于对区块链技术的深入理解以及来自运营比太钱包的多年经验，比特派致力于为全球用户提供安全的资产管理以及丰富的区块链应用服务。使用比特派，用户可以在方便的进行交易及使用应用服务的同时确保资产100%由自己掌控。",
        "By emphasizing the importance of asset safety, we put great effort on security and receive a good reputation in this respect. Therefore our bitcoin wallet “Bither” is listed on":"我们极为重视安全，在安全方面投入了大量的精力并享有良好的声誉。也正因此，我们开发的比特币钱包-比太(Bither)被作为推荐钱包列入",
        "as recommended wallet.":"。",
        "The world is adapting to blockchain quickly, but explore the blockchain world is not easy. We are working hard to make Bitpie as your key to the new world.":"世界正在加速向区块链转移,但想要探索这个世界并不容易。我们正在努力让比特派成为您通往新世界的钥匙。",
        "Bitpie's main office place is located in Sydney.":"比特派主要办公地点位于澳大利亚悉尼市。",
        "Address":"地址",
        "About Us":"关于我们",
        "a safe and easy way to manage and trade your multi-blockchain (Bitcoin) assets":"安全方便的管理和交易多种区块链（比特币）资产",
        "full":"(已满)",
        "under":"(未满)",
        "Announcement":"公告",
        "Scheduled Server Upgrade Notification":"服务器计划升级通知",
        "In order to provide better service quality and trading experience, Bitpie will conduct server upgrade on 14:30, Dec. 4th, 2017 (UTC +0).  During the upgrade, wallet function will not be accessible, trading will be suspended. The estimated upgrade time can be as long as 2 hours, the service resume time will be 16:30, Dec. 4th, 2017 (UTC +0).":"为了向用户提供更加优质的服务和交易体验，比特派将在香港时间 2017年12月5日00:30 - 2:30期间进行服务器升级。届时，您将不能进行收发币、一键买卖、派银行转入转出、点对点交易等操作。",
        "Bitpie Team":"比特派团队",
        "We apologize for any inconvenience this upgrade may cause and appreciate your patience.":"请您提前做好相关规划，感谢您的理解与支持。",
        "jobs":"加入我们",
        "New":"相关报道",
        "Bither Download":'比太下载',
        "Desktop":"桌面版",
        "Settings-General-Device Management":"2.在手机的设置-通用-描述文件与设备管理，信任下面的文件",
        "Settings-Cellular":"1.进入设置-蜂窝移动网络-使用无线局域网与蜂窝移动的应用，随便找款App(例：这里选择的是比太)",
        "Please save this URL:":"请记住此下载网址:",
        "Please open this address in Safari.":"微信请点击右上角(三点),选择用Safari浏览器打开",
        "(only for company internal personnel)":"（本版本仅限于公司内部人员使用)",
        "Tap the button below('install'), the App will be installed automatically":"点击下方(点击安装)按钮,系统将自动安装",
        "This version is same as App Store version.":"此版本与 App Store 版本一致",
        "Install":'点击安装',
        "for iOS device":"适用于iOS设备",
        "or Scan QR Code as below":"或者用手机扫描下面的二维码安装",
        "Bitpie iOS Installation Tutorial":"bitpie iOS安装教程",
        "1.Open Bitpie for the first time, you’ll see this:":"1.第一次打开bitpie的时候会弹出如下框：",
        "2.Settings-General-Device Management, trust the file below:":"2.在手机的设置-通用-描述文件与设备管理，信任下面的文件：",
        "3.Trust the following certificate, then you can successfully launch Bitpie App.":"3.信任下面的证书就可以启动bitpie了。",
        "Solution for no prompt in iOS 10 (allowing App using WLAN & Cellular), App cannot be used:":"iOS 10 不提示(是否允许应用访问数据)，导致应用无法使用的解决方案",
        "1.Settings-WLAN-Apps Using WLAN & Cellular":"1.进入设置-蜂窝移动网络-使用无线局域网与蜂窝移动的应用，随便找款App(例：这里选择的是比太)",
        "2.Choose an App (any one is OK): hereby we choose Bither":"2.更改一下设置即可(任意更改)。",
        "3.Enter Bitpie App, you will see the prompt. Press ok":"3.然后进入bitpie App就会提示是否允许使用数据。选择充许就可以了。",
        "ExPie transaction fees":"ExPie 交易费率",
        "Transaction fees list":"交易费率列表",
        "Transaction pairs":"交易对",
        "Transaction fees":"交易费率",
        "Note:":"备注:",
        "Tranacrion fees will be deducted from the received assets. 50% of fees for VIP users.":"(交易费）扣除收取到的资产。VIP用户交易费率5折。",
        "Withdrawal":"提现",
        "The above manual review, audit will be completed within 24 hours.":"以上需进行人工审核，审核会在24小时内完成。",
        "If you want to receive the coins immediately, pls do not withdraw coins over the limits. If withdrawal amount is over the limit, we will carry out the manual verifications.":"如果您需要提现即时到账，请不要超过对应币种的提现数量，不用人工审核。",
        "Pie Bank Withdrawal":"派银行提现",
        "Deposits are On-Chain transactions, so you need to wait for confirmations.":"充值是链上交易，所以需要等待确认。",
        "Confirmations":"确认数",
        "Amount":'数量',
        "Deposits coin":"充值币种",
        "1.Trades between VIPs":"1、VIP与VIP之间的交易 ",
        "2.Trades between VIPs and common users":"2、VIP与普通用户之间的交易 ",
        "3.Trades between users who paid deposit and common users":"3、押金用户与普通用户之间的交易 ",
        "fees only on users who post advertisements, no fees on common users":"只对广告方收取服务费(单方向)，普通用户不收取。",
        "BTC Fees":"BTC服务费率列表",
        "Other Coins Fees":"其它币种服务费率列表",
        "OTC Trade Fees":"OTC 服务费率",
        "Instructions for Pie Bank Withdrawal":"派银行充值提现说明",
        "and":"且",
        "Pie Bank Deposits":"派银行充值",
        "Test":"企业版",
        "Enterprise Version is Unavailable Temporarily. Please Install Bitpie App from App Store":"Bitpie 企业版不可用，请通过海外的 App Store 账户安装 Bitpie",
        "Viewed:":"阅读："
    }
}

Lang.prototype.pack.jp = {
    "token":{
        "Bitpie - Your key to the blockchain world":'Bitpie - 最も使いやすいビットコインウォレット',
        "bitpie - Best Bitcoin Wallet!":"",
        "Bitpie":"ビットパイ",
        "Android":"アンドロイド",
        "Download":"ダウンロード",
        "Google Play":"グーグルストア",
        "iOS":"アップル",
        "App Store":"アップルストア",
        "Bither":"",
        "Wallets":"ウォレット",
        "Bither Wallet":"Bither ウォレット",
        "technology.":"技术.",
        "Bitpie Android":"ビットパイ　アンドロイド",
        "Bitpie iOS":'ビットパイ iOS',
        "Version:":"バージョン：",
        "New":"関連記事",
        "Use your cell phone  to install by scaning the qr code":"下のQRコードをスキャンしてインストールすることもできます",
        "Doc":"ヘルプ",
        "BITPIE LIMITED was registered at Republic of Seychelles since 2015":"BITPIE LIMITEDは2015年にセイシェル共和国に登録され",
        "Bitpie iOS app is under operation of Bitpie Canada":"Bitpie iOSはBitpie Canadaによって運営されています",
        "Blog":"ブログ",
        "blog":"ブログ",
        "Written by":"作者",
        "Certificate":"证书",
        "Close":"关闭",
        "BITPIE Terms of Service":"ビットパイ利用規約",
        "An easy-to-use wallet service, you can easily manage your multi-blockchain assets.":"使いやすいウォレットサービスで手軽にロックチェーン資産を管理する",
        "Trade your asset with users all over the world in the build-in OTC and exchange(3rd party services).":"OTCと取引所（第三者サービス）内臓し、世界各地の使用者と手軽に通貨為替取引とOTC取引をできる",
        "By holding private key only by yourself, no one else can access your assets.":"自分でコントロール秘密鍵によって、他にお客様の資産に触れる人はいない",
        "Build-in professional KYC/anti-fraud system and commit to meet regulation and compliance.":"プロのKYCと詐欺防止システムを内蔵し、規制と法律を守ることに力を入れる",
        "Originate from Bither team, Bitpie team is made up of blockchain professionals and business experts from IT/ Financial industries based around the world.":"ビッタイに生まれ、ビットパイ団体は世界各地のブロックチェーン専門家及びITサービスと金融の専門家で結成している。",
        "With strong technical strength on blockchain and years of experience from operate bither wallet, Bitpie is devoted to be a service provider to bring global users with safe asset management and broad blockchain application access. With Bitpie, users can trade assets with others or use their asset in more coming scenarios meanwhile keep their asset 100% self-controllable.":"ブロックチェーン技術の深い理解及びビッタイウォレットを長年運営した経験に基づき、ビットパイは全世界のユーザーに安全な資産管理と豊富なブロックチェーン応用サービスを提供することに力を入れている。ビットパイを利用し、ユーザーは手軽に取引すると応用サービスを使うと同時に100％自分で資産をコントロールすることを確保する。",
        "By emphasizing the importance of asset safety, we put great effort on security and receive a good reputation in this respect. Therefore our bitcoin wallet “Bither” is listed on":"我々は安全の重視を極めている、安全面に大量の精力を投入し、よい評判をもっている。そのために、我々が開発したビットコインウォレット-ビッタイ(Bither)は",
        "as recommended wallet.":"に推奨している。",
        "The world is adapting to blockchain quickly, but explore the blockchain world is not easy. We are working hard to make Bitpie as your key to the new world.":"世界は加速してブロックチェーンに移行している、しかしこの世界を探索することは容易ではない、我々はビットパイをあなたの新世界への鍵になることを努力している。",
        "Bitpie's main office place is located in Sydney.":"ビットパイの主要事務所はオーストラリアのシドニーにある。",
        "Address":"住所",
        "About Us":"弊社について",
        "a safe and easy way to manage and trade your multi-blockchain (Bitcoin) assets":"安全、便利的にブロックチェーン（ビットコイン）資産を管理とトレードする",
        "full":"(已满)",
        "under":"(未满)",
        "Announcement":"公告",
        "Scheduled Server Upgrade Notification":"服务器计划升级通知",
        "In order to provide better service quality and trading experience, Bitpie will conduct server upgrade on 14:30, Dec. 4th, 2017 (UTC +0).  During the upgrade, wallet function will not be accessible, trading will be suspended. The estimated upgrade time can be as long as 2 hours, the service resume time will be 16:30, Dec. 4th, 2017 (UTC +0).":"为了向用户提供更加优质的服务和交易体验，比特派将在香港时间 2017年12月5日00:30 - 2:30期间进行服务器升级。届时，您将不能进行收发币、一键买卖、派银行转入转出、点对点交易等操作。",
        "Bitpie Team":"比特派团队",
        "We apologize for any inconvenience this upgrade may cause and appreciate your patience.":"请您提前做好相关规划，感谢您的理解与支持。",
        "Bither Download":'ビタイダウンロード',
        "Desktop":"PC",
        "Settings-General-Device Management":"2.在手机的设置-通用-描述文件与设备管理，信任下面的文件",
        "Settings-Cellular":"1.进入设置-蜂窝移动网络-使用无线局域网与蜂窝移动的应用，随便找款App(例：这里选择的是比太)",
        "Please save this URL:":"ダウンロードURL：",
        "Please open this address in Safari.":"微信请点击右上角(三点),选择用Safari浏览器打开",
        "(only for company internal personnel)":"（このバージョンは内部テスト専用)",
        "Tap the button below('install'), the App will be installed automatically":"点击下方(点击安装)按钮,系统将自动安装",
        "This version is same as App Store version.":"このバージョンはApp Storeバージョンと一致しています",
        "Install":'インストール',
        "for iOS device":"iOS対応",
        "or Scan QR Code as below":"下のQRコードをスキャンしてインストールすることもできます",
        "Bitpie iOS Installation Tutorial":"Bitpie iOSインストール説明",
        "1.Open Bitpie for the first time, you’ll see this:":"1.初めてbitpieを開く時は下のダイアログが出てきます：",
        "2.Settings-General-Device Management, trust the file below:":"2.｣ｱ｣ｮ	設定‐一般‐プロファイルとデバイス管理で、下のファイルを信頼してください：",
        "3.Trust the following certificate, then you can successfully launch Bitpie App.":"3.データ通信の使用を許可すれば使えるようになります。",
        "Solution for no prompt in iOS 10 (allowing App using WLAN & Cellular), App cannot be used:":"iOS 10　データ通信の許可を提示しなくて使えない場合の解決方法",
        "1.Settings-WLAN-Apps Using WLAN & Cellular":"1.｣ｱ｣ｮ	設定‐モバイルデータ通信‐Wi-Fiとモバイルデータを使うアプリ、その中のどれでも一つ選んでください。",
        "2.Choose an App (any one is OK): hereby we choose Bither":"2.設定を変えれば、今回アプリを開いた時ダイアログが出てきます。",
        "3.Enter Bitpie App, you will see the prompt. Press ok":"3.その後、bitpie Appはデータの使用を許可するかと尋ね、それを許可してください。",
        "ExPie transaction fees":"ExPie 取引料率",
        "Transaction fees list":"ExPie 取引料率表",
        "Transaction pairs":"通貨種類",
        "Transaction fees":"取引料率",
        "Note:":"注:",
        "Tranacrion fees will be deducted from the received assets. 50% of fees for VIP users.":"（引料は）受け取った資産を控除させていただきます。VIPユーザー様の取引料率は5割引をお付けします",
        "Withdrawal":"提现",
        "The above manual review, audit will be completed within 24 hours.":"以上お引出しすると人工審査が必要となるので、審査は２４時間以内に完了となります。",
        "If you want to receive the coins immediately, pls do not withdraw coins over the limits. If withdrawal amount is over the limit, we will carry out the manual verifications.":"お急ぎの場合は、上記を超えないようにお引出しすることがお勧めとなります。",
        "Pie Bank Withdrawal":"パイ銀行お引出し",
        "Deposits are On-Chain transactions, so you need to wait for confirmations.":"お預入はオンチェーンとなるので、確認を待つことが必要となります。",
        "Confirmations":"確認数",
        "Amount":'数量',
        "Deposits coin":"通貨種類",
        "1.Trades between VIPs":"1、VIP同士の取引 ",
        "2.Trades between VIPs and common users":"2、VIPと普通ユーザーの取引 ",
        "3.Trades between users who paid deposit and common users":"3、証拠金ユーザーと普通ユーザーの取引 ",
        "fees only on users who post advertisements, no fees on common users":"　広告した方だけでサービス料を頂戴致します、普通ユーザーは無料となります",
        "BTC Fees":"BTCサービス料率表",
        "Other Coins Fees":"他の通貨サービス料率表",
        "OTC Trade Fees":"OTCサービス料率",
        "Instructions for Pie Bank Withdrawal":"派银行充值提现说明",
        "and":"また",
        "Pie Bank Deposits":"パイ銀行お預入",
        "Bither - a simple and secure Bitcoin Wallet!":"Bither-シンプル、安全的なビットコインウォレット",
        "Test":"企業版",
        "Viewed:":"閲読:"
    }
}