/**
 * Created by test on 16/11/25.
 */
Lang.prototype.pack.zh = {
    "token":{
        "bitpie - Best Bitcoin Wallet!":"比特派-最好用的比特币钱包！",
        "About":"关于",
        "Features":"特色",
        "Contact":"联系我们",
        "Bitpie":"比特派",
        "Wallet & Ｍultisig Service":"钱包 & 多重签名服务",
        "Multisig Service":"多重签名服务",
        "Android":"安卓",
        "Download":"下载",
        "Google Play":"谷歌商店",
        "iOS":"苹果",
        "App Store":"苹果商店",
        "Bitpie is developed by":"比特派是由",
        "Bither":"比太",
        "team. With bitpie, you can have a secured bitcoin wallet as simple as possible, and you can also buy/sell bitcoins in an easy way(not available in China).":
            "团队研发的比特币钱包，它能让您轻松安全的使用比特币，并且还能方便的买卖比特币(不支持中国大陆)。",
        "Bitpie  supports multi-blockchain assets, so a wallet can manage everything. Try it now quickly!":
            "比特派支持多种区块链资产，您可以使用一个钱包来管理一切，赶紧试试吧！",
        "Wallets":"钱包",
        "Simpliest Bitcoin Wallet Ever!":"简单易用的比特币钱包！",
        "As a bitcoin wallet, bitpie means you control your private keys, and nobody can touch your assets. With our special design, you do not need to sync the blockchain data with the bitcon network, and sending/receiving bitcoins are processed so quickly. Also bitpie supports dynamic transaction fee and transaction accelerator, that means your transaction can easily go through even when network congestion.":
            "作为钱包，比特派意味着您自己掌握私钥，其他人无法触碰您的财产。通过我们的优化，您可以快捷的收发比特币，并且比特派还支持动态矿工费及交易加速器，这意味着即便是遇到了网络大拥堵，您的交易也能迅速得到确认。",
        "P2P Exchange:Easiest Way to Buy/Sell Bitcoins with Other Peers!":"P2P 交易：轻松的与其他人兑换比特币！",
        "Bitpie has built-in escrow function based on Multisig technology services, so you can easily exchange bitcoins with the dealers all over the world in a secured environment.":"比特派内置了基于多重签名技术服务，因此您可以安全的与世界各地的交易员兑换比特币。",
        "Security":"安全：",
        "Bither team has so many reputations in the past, and Bither wallet has been recommended by Bitcoin.org for a long time. We know how to make secured bitcoin wallet, and how to protect your blockchain assets. The bitpie wallet is totally based on Bither technology, so it is robust and trustable.":
            "比太团队在安全方面一直享有良好的声誉，比太钱包也是中国唯一一个被 Bitcoin.org 官方推荐的比特币钱包，我们懂得如何开发安全的比特币钱包以及如何保护您的区块链资产，比特派钱包完全基于比太技术，值得信赖。",
        "Bither team has so many reputations in the past, and Bither wallet has been recommended by":"比太团队在安全方面一直享有良好的声誉，比太钱包也是中国唯一一个被",
        "for a long time. We know how to make secured bitcoin wallet, and how to protect your blockchain assets. The bitpie wallet is totally based on Bither technology, so it is robust and trustable.":"官方推荐的比特币钱包，我们懂得如何开发安全的比特币钱包以及如何保护您的区块链资产，比特派钱包完全基于比太技术，值得信赖。",
        "Keep in Touch:":"保持联络",
        "P2P Exchange":"P2P 交易：",
        "Wallets":"钱包：",
        "Easiest Way To Exchange Bitcoins With Other Peers!":"轻松的与其他人兑换比特币！",
        "Email":"邮箱",
        "Telegram":"电报群(Telegram)",
        "QQ group 1:493077876":"QQ群1：493077876(已满)",
        "QQ group 2:431191173":"QQ群2：431191173(已满)",
        "QQ group 3:616697070":"QQ群3：616697070(已满)",
        "QQ group 4:602675609":"QQ群4：602675609(已满)",
        "QQ group 5:334102375":"QQ群5：334102375(未满)",
        "Home":"首页",
        "The bitpie wallet is based on":"比特派钱包基于",
        "Bither":"比太",
        "technology.":"技术.",
        "Bitpie Android":"比特派 安卓",
        "Version:":"版本：",
        "Download":"下载",
        "Use your cell phone  to install by scaning the qr code":"或者用手机扫描下面的二维码安装",
        "Doc":"帮助",
        "BITPIE LIMITED registered at Republic of Seychelles":"BITPIE LIMITED 注册于塞舌尔共和国",
        "Blog":"博客",
        "blog":"博客",
        "Written by":"作者",
        "Certificate":"证书",
        "Close":"关闭",
        "BITPIE Terms of Service":"比特派用户协议",
        "An easy-to-use wallet service, you can easily manage your multi-blockchain assets.":"易于使用的钱包服务使您可以轻松的管理多种区块链资产。",
        "Trade your asset with users all over the world in the build-in OTC and exchange(3rd party services).":"内置OTC及交易所(第三方服务)，让您方便的与世界各地的用户进行币币交易及OTC交易。",
        "By holding private key only by yourself, no one else can access your assets.":"通过您自己掌控私钥，没有其他人能够触碰您的资产。",
        "Build-in professional KYC/anti-fraud system and commit to meet regulation and compliance.":"内置专业KYC及防欺诈系统，致力于遵守监管和法律合规。",
        "Originate from Bither team, Bitpie team is made up of blockchain professionals and business experts from IT/ Financial industries based around the world.":"源自比太，比特派团队由来自世界多地的区块链技术专家和IT服务及金融行业的业务专家组成。",
        "With strong technical strength on blockchain and years of experience from operate bither wallet, Bitpie is devoted to be a service provider to bring global users with safe asset management and broad blockchain application access. With Bitpie, users can trade assets with others or use their asset in more coming scenarios meanwhile keep their asset 100% self-controllable.":"基于对区块链技术的深入理解以及来自运营比太钱包的多年经验，比特派致力于为全球用户提供安全的资产管理以及丰富的区块链应用服务。使用比特派，用户可以在方便的进行交易及使用应用服务的同时确保资产100%由自己掌控。",
        "By emphasizing the importance of asset safety, we put great effort on security and receive a good reputation in this respect. Therefore our bitcoin wallet“Bither”is listed on":"我们极为重视安全，在安全方面投入了大量的精力并享有良好的声誉。也正因此，我们开发的比特币钱包-比太(Bither)被作为推荐钱包列入",
        "as recommended wallet.":"。",
        "The world is adapting to blockchain quickly, but explore the blockchain world is not easy. We are working hard to make Bitpie as your key to the new world.":"世界正在加速向区块链转移,但想要探索这个世界并不容易。我们正在努力让比特派成为您通往新世界的钥匙。",
        "Bitpie's main office place is located in Sydney.":"比特派主要办公地点位于澳大利亚悉尼市。",
        "Address":"地址",
        "About Us":"关于我们",
        "a safe and easy way to manage and trade your multi-blockchain assets":"安全方便的管理和交易多种区块链资产"

    }
}